### ISSUE TITLE
'libgcc_s_dw2-1.dll' missing in v0.0.17

### ISSUE THREAD

**Issue by Miragecoder** [RyanBabij/WorldSim#3]
Upon executing the latest build:
https://github.com/RyanBabij/WorldSim/releases/tag/v0.0.017-dev

...perhaps some static linking will help?
https://stackoverflow.com/questions/4702732/the-program-cant-start-because-libgcc-s-dw2-1-dll-is-missing

Edit: At runtime I also seem to be missing 'libwinpthread-1.dll'.

Edit 2: I also tip my hat to this project. 😄

**Comment by RyanBabij** [comment]
Oops. It looks like I accidentally released a debug build, I should be more careful 😅. I have just reuploaded builds with static linking. Thankyou for letting me know, and also thanks for the kind words, I am happy to see people interested in the project. 😊
