### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by mcejp** [RyanBabij/WorldSim#4]
I have been trying to create a working CMakeLists file in https://github.com/mcejp/WorldSim/commits/master, but I am getting a ton of errors about missing declarations and so on. Am I doing something wrong or is the code currently in a non-buildable state?

**Comment by RyanBabij** [comment]
Hi Martin,
I'm afraid the code is currently in a non-buildable state, however it
should technically be possible to build. The code requires the Wildcat
library which is one of my repositories. You will likely also need to link
some libraries: Glew, FreeGlut, OpenAL and POSIX threads if memory serves.
I typically compile with clang++ and g++ with mingw. I don't have any
experience with makefiles so I just use the compiler directly. My
compilation command for development is:

clang++ -target i686-pc-windows-gnu Driver.cpp -I %WILDCAT%\ -I
%WILDCAT%\Lib\ -L %WILDCAT%\Lib\ -std=c++17 -lglew32 -lfreeglut_static
-lopengl32 -lglu32 -m32 -lwinmm -lgdi32 -pthread -Wall -Wshadow
-Wpointer-arith -Wcast-qual -Wextra -Wno-unused-variable
-Wno-unused-parameter -Wno-unused-const-variable -Wno-unused-value
-Wl,--large-address-aware

and my compilation command for builds is currently:

g++ Driver.cpp -I %WILDCAT%\ -I %WILDCAT%\Lib\ -L %WILDCAT%\Lib\ -std=c++17
-lfreeglut_static -lopengl32 -lglu32 -lwinmm -lgdi32 -pthread -m32 -Wall
-Wshadow -Wpointer-arith -Wcast-qual -Wextra -Wno-unused-variable
-Wno-unused-parameter -Wno-unused-const-variable -Wno-unused-value
-Wl,--large-address-aware -static-libgcc -static-libstdc++
-fno-strict-overflow -flto -fno-rtti -pipe -fno-exceptions
-ffunction-sections -fdata-sections -Wl,--gc-sections -O3 -s

I haven't tested on Linux for a while so there may be issues getting it to
compile on that OS.

I've attached my current Wildcat library in case there are any issues
getting it off my Github.

I hope you find this helpful, do let me know if you require any more info.

Regards,
Ryan Babij

**Comment by mcejp** [comment]
Ah, this explains a lot. I am aware about the Wildcat library; my main mistake was trying to compile and link the individual sources instead of just Driver.cpp.
I will retry and let you know. Btw, this was on Linux.

**Comment by mcejp** [comment]
I was able to build WorldSim in Visual Studio 2019. In the end it was mostly a matter of including and configuring Wildcat and FreeGLUT. I ran into a compile error with `__attribute__((unused))` in one point, otherwise it went surprisingly smoothly.

I'd like to retry with Linux at some point, but it seemed like there were functions missing.

**Comment by RyanBabij** [comment]
Excellent, I'm glad it worked out. I test it on linux from time to time, so
I'll see if I can get a cross-platform release sorted next time.

**Comment by mcejp** [comment]
FYI, [here](https://github.com/mcejp/WorldSim/runs/450615501?check_suite_focus=true) you can see the compile errors occurring on Linux.

**Comment by RyanBabij** [comment]
Thanks, it looks like threading is the main issue with the Linux build.
I'll see if I can get that working

**Comment by RyanBabij** [comment]
Okay I just updated most of the code to get it compiling on Linux. It compiles on my Linux with no issues and seems to run fine with the following command:

clang++ Driver.cpp -I /PATH_TO_WILDCAT -static-libgcc -static-libstdc++ -pthread -std=c++14 -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-unused-const-variable -Wno-unused-value -Wno-unused-private-field -lGL -lGLU -lglut

**Comment by mcejp** [comment]
Cool! I've updated my branch, it builds in CI too :)

Windows build in CI is running into an issue with non-existent <sys/time.h> included from Timer.hpp, but it's a bit strange, I was able to compile and run it last week.

**Comment by RyanBabij** [comment]
It seems that <sys/time.h> is not Windows standard, probably requires MingW or something. I'll have to look into a Windows-specific implementation

**Comment by mcejp** [comment]
Ah, right.

You may want to look into std::chrono, it should solve your needs portably
⁣

**Comment by RyanBabij** [comment]
I just finished some Windows-specific code using GetTickCount() but I'll have a look at std::chrono
