### ISSUE TITLE
How to activate Adventure mode?

### ISSUE THREAD

**Issue by mcejp** [RyanBabij/WorldSim#7]
I don't get it 😭

**Comment by RyanBabij** [comment]
Oh sorry I think I broke Adventure mode in Linux. Linux is currently compiling without threads so it probably broke some stuff. I'll try get it fixed today

**Comment by RyanBabij** [comment]
Ok I fixed in latest version: 38a53dce4f48a0e0cc2c38d0d4f14176946ca6d4

**Comment by RyanBabij** [comment]
Oh btw to enter Adventure mode, from World Generator menu press 2 to enter Simulator Mode. From here press Tab and you should enter Adventure Mode. WASD to walk around etc.

**Comment by RyanBabij** [comment]
New build instructions have been added
